"""
Module: workspace.field_rows

Role:
- Define named row indices for workspace-owned field slabs.

Notes:
- Constants live in a dependency-free module so both workspace accessors and
  engine kernels can share the same row contract.
- These names describe row layout only; they do not own memory.
"""

from __future__ import annotations

GEOMETRY_SURFACE_SIN_TB = 0
GEOMETRY_SURFACE_R = 1
GEOMETRY_SURFACE_R_T = 2
GEOMETRY_SURFACE_Z_T = 3
GEOMETRY_SURFACE_J = 4
GEOMETRY_SURFACE_JDIVR = 5
GEOMETRY_SURFACE_GRTDIVJR_T = 6
GEOMETRY_SURFACE_GTTDIVJR = 7
GEOMETRY_SURFACE_GTTDIVJR_R = 8

GEOMETRY_RADIAL_S_R = 0
GEOMETRY_RADIAL_V_R = 1
GEOMETRY_RADIAL_KN = 2
GEOMETRY_RADIAL_KN_R = 3
GEOMETRY_RADIAL_LN_R = 4

RESIDUAL_ROOT_PSIN = 0
RESIDUAL_ROOT_PSIN_R = 1
RESIDUAL_ROOT_PSIN_RR = 2
RESIDUAL_ROOT_FFN_PSIN = 3
RESIDUAL_ROOT_PN_PSIN = 4

RESIDUAL_SURFACE_G = 0
RESIDUAL_SURFACE_GPSIN_R = 1
RESIDUAL_SURFACE_GPSIN_Z = 2
RESIDUAL_SURFACE_GPSIN_R_SIN_TB = 3

PROFILE_VALUE = 0
PROFILE_R = 1
PROFILE_RR = 2

GRID_RADIAL_RHO = 0
GRID_RADIAL_X = 1
GRID_RADIAL_Y = 2
GRID_RADIAL_RHO_POWERS_START = 3

GRID_POLOIDAL_THETA = 0
GRID_POLOIDAL_COS_MTHETA_START = 1
