// CMinpack adapter implementations for generated Cxx Kernel artifacts.

#include "nonlinear.h"
#include <cminpack.h>

namespace nonlinear::detail::cminpack
{
    int lmdif(FuncMN  callback,
              void*   data,
              int     m,
              int     n,
              double* x,
              double* fvec,
              double  ftol,
              double  xtol,
              double  gtol,
              int     max_evaluations,
              double  epsfcn,
              double* diag,
              int     mode,
              double  factor,
              int     nprint,
              int*    nfev,
              double* fjac,
              int     ldfjac,
              int*    ipvt,
              double* qtf,
              double* wa1,
              double* wa2,
              double* wa3,
              double* wa4)
    {
        return ::lmdif(callback,
                       data,
                       m,
                       n,
                       x,
                       fvec,
                       ftol,
                       xtol,
                       gtol,
                       max_evaluations,
                       epsfcn,
                       diag,
                       mode,
                       factor,
                       nprint,
                       nfev,
                       fjac,
                       ldfjac,
                       ipvt,
                       qtf,
                       wa1,
                       wa2,
                       wa3,
                       wa4);
    }

    int lmder(FuncDerMN callback,
              void*     data,
              int       m,
              int       n,
              double*   x,
              double*   fvec,
              double*   fjac,
              int       ldfjac,
              double    ftol,
              double    xtol,
              double    gtol,
              int       max_evaluations,
              double*   diag,
              int       mode,
              double    factor,
              int       nprint,
              int*      nfev,
              int*      njev,
              int*      ipvt,
              double*   qtf,
              double*   wa1,
              double*   wa2,
              double*   wa3,
              double*   wa4)
    {
        return ::lmder(callback,
                       data,
                       m,
                       n,
                       x,
                       fvec,
                       fjac,
                       ldfjac,
                       ftol,
                       xtol,
                       gtol,
                       max_evaluations,
                       diag,
                       mode,
                       factor,
                       nprint,
                       nfev,
                       njev,
                       ipvt,
                       qtf,
                       wa1,
                       wa2,
                       wa3,
                       wa4);
    }
} // namespace nonlinear::detail::cminpack
