// System CMINPACK driver adapters for deliberately remote generated-kernel fallbacks.

#include <cminpack.h>

namespace nonlinear::detail::standard_cminpack
{
    int hybrd(int (*callback)(void*, int, const double*, double*, int),
              void* data,
              int n,
              double* x,
              double* fvec,
              double xtol,
              int max_evaluations,
              int ml,
              int mu,
              double epsfcn,
              double* diag,
              int mode,
              double factor,
              int nprint,
              int* nfev,
              double* fjac,
              int ldfjac,
              double* r,
              int lr,
              double* qtf,
              double* wa1,
              double* wa2,
              double* wa3,
              double* wa4)
    {
        return ::hybrd(callback,
                       data,
                       n,
                       x,
                       fvec,
                       xtol,
                       max_evaluations,
                       ml,
                       mu,
                       epsfcn,
                       diag,
                       mode,
                       factor,
                       nprint,
                       nfev,
                       fjac,
                       ldfjac,
                       r,
                       lr,
                       qtf,
                       wa1,
                       wa2,
                       wa3,
                       wa4);
    }

    int hybrj(int (*callback)(void*, int, const double*, double*, double*, int, int),
              void* data,
              int n,
              double* x,
              double* fvec,
              double* fjac,
              int ldfjac,
              double xtol,
              int max_evaluations,
              double* diag,
              int mode,
              double factor,
              int nprint,
              int* nfev,
              int* njev,
              double* r,
              int lr,
              double* qtf,
              double* wa1,
              double* wa2,
              double* wa3,
              double* wa4)
    {
        return ::hybrj(callback,
                       data,
                       n,
                       x,
                       fvec,
                       fjac,
                       ldfjac,
                       xtol,
                       max_evaluations,
                       diag,
                       mode,
                       factor,
                       nprint,
                       nfev,
                       njev,
                       r,
                       lr,
                       qtf,
                       wa1,
                       wa2,
                       wa3,
                       wa4);
    }

    int lmdif(int (*callback)(void*, int, int, const double*, double*, int),
              void* data,
              int m,
              int n,
              double* x,
              double* fvec,
              double ftol,
              double xtol,
              double gtol,
              int max_evaluations,
              double epsfcn,
              double* diag,
              int mode,
              double factor,
              int nprint,
              int* nfev,
              double* fjac,
              int ldfjac,
              int* ipvt,
              double* qtf,
              double* wa1,
              double* wa2,
              double* wa3,
              double* wa4)
    {
        return ::lmdif(callback,
                       data,
                       m,
                       n,
                       x,
                       fvec,
                       ftol,
                       xtol,
                       gtol,
                       max_evaluations,
                       epsfcn,
                       diag,
                       mode,
                       factor,
                       nprint,
                       nfev,
                       fjac,
                       ldfjac,
                       ipvt,
                       qtf,
                       wa1,
                       wa2,
                       wa3,
                       wa4);
    }

    int lmder(int (*callback)(void*, int, int, const double*, double*, double*, int, int),
              void* data,
              int m,
              int n,
              double* x,
              double* fvec,
              double* fjac,
              int ldfjac,
              double ftol,
              double xtol,
              double gtol,
              int max_evaluations,
              double* diag,
              int mode,
              double factor,
              int nprint,
              int* nfev,
              int* njev,
              int* ipvt,
              double* qtf,
              double* wa1,
              double* wa2,
              double* wa3,
              double* wa4)
    {
        return ::lmder(callback,
                       data,
                       m,
                       n,
                       x,
                       fvec,
                       fjac,
                       ldfjac,
                       ftol,
                       xtol,
                       gtol,
                       max_evaluations,
                       diag,
                       mode,
                       factor,
                       nprint,
                       nfev,
                       njev,
                       ipvt,
                       qtf,
                       wa1,
                       wa2,
                       wa3,
                       wa4);
    }
} // namespace nonlinear::detail::standard_cminpack
